import { 
  ContractItem, 
  ProbationItem, 
  ContractStatus, 
  ProbationStatus,
  UserRecommendation, 
  ApprovalStatus, 
  SalaryNegotiationStatus,
  PriorityType
} from "./types";

export const INITIAL_CONTRACTS: ContractItem[] = [
  {
    id: "EMP-001",
    employeeId: "EMP-001",
    employeeName: "Aditya Pratama",
    department: "Engineering",
    position: "Senior Frontend Engineer",
    directManager: "Budi Santoso",
    contractType: "PKWT II",
    contractNumber: "021/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-03",
    contractEndDate: "2026-07-02",
    daysRemaining: 2,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.Resolved,
    negotiationNotes: "Compensation review sudah resolved. Nominal dikelola di luar sistem.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Approved,
    headHRReview: ApprovalStatus.Approved,
    contractDraftDate: "2026-06-25",
    contractSentDate: "2026-06-28",
    signedDeadline: "2026-07-01",
    signedReceivedDate: "",
    contractStatus: ContractStatus.Critical,
    salaryNegotiationStatus: SalaryNegotiationStatus.Resolved,
    hrPic: "Siti Rahma",
    notes: "Tinggal menunggu tanda tangan kembali dari karyawan. Compensation review sudah resolved by Management/Payroll. Detail nominal dikelola di luar sistem.",
    priority: "Critical"
  },
  {
    id: "EMP-002",
    employeeId: "EMP-002",
    employeeName: "Dewi Lestari",
    department: "Marketing",
    position: "Social Media Specialist",
    directManager: "Indah Wahyuni",
    contractType: "PKWT I",
    contractNumber: "089/HRD-PKWT/VI/2025",
    contractStartDate: "2025-06-15",
    contractEndDate: "2026-06-15",
    daysRemaining: -15,
    compensationReviewNeeded: false,
    negotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    negotiationNotes: "",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Pending,
    headHRReview: ApprovalStatus.Pending,
    contractDraftDate: "",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.Overdue,
    salaryNegotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    hrPic: "Rian Hidayat",
    notes: "OVERDUE! Belum ada rekomendasi final dari user karena terlewat bulan lalu. Segera follow up Manager Marketing.",
    priority: "Overdue"
  },
  {
    id: "EMP-003",
    employeeId: "EMP-003",
    employeeName: "Rian Cahyono",
    department: "Operations",
    position: "Logistics Coordinator",
    directManager: "Joko Susilo",
    contractType: "PKWT II",
    contractNumber: "102/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-06",
    contractEndDate: "2026-07-05",
    daysRemaining: 5,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.Resolved,
    negotiationNotes: "Rekomendasi disetujui, siap draft kontrak.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Approved,
    headHRReview: ApprovalStatus.Approved,
    contractDraftDate: "2026-06-20",
    contractSentDate: "2026-06-25",
    signedDeadline: "2026-07-04",
    signedReceivedDate: "",
    contractStatus: ContractStatus.WaitingSignedContract,
    salaryNegotiationStatus: SalaryNegotiationStatus.Resolved,
    hrPic: "Siti Rahma",
    notes: "Draft kontrak sudah dikirimkan, sedang menunggu dokumen signed kembali.",
    priority: "High"
  },
  {
    id: "EMP-004",
    employeeId: "EMP-004",
    employeeName: "Siti Aminah",
    department: "Finance & Accounting",
    position: "Tax Assistant",
    directManager: "Megawati Kusuma",
    contractType: "PKWT I",
    contractNumber: "115/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-10",
    contractEndDate: "2026-07-09",
    daysRemaining: 9,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.Resolved,
    negotiationNotes: "Nego alot disetujui. Kontrak fisik sudah dikirim.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Approved,
    headHRReview: ApprovalStatus.Approved,
    contractDraftDate: "2026-06-26",
    contractSentDate: "2026-06-29",
    signedDeadline: "2026-07-08",
    signedReceivedDate: "",
    contractStatus: ContractStatus.ContractSent,
    salaryNegotiationStatus: SalaryNegotiationStatus.Resolved,
    hrPic: "Rian Hidayat",
    notes: "Negosiasi kompensasi disetujui setelah diskusi intensif. Kontrak fisik sudah dikirim.",
    priority: "High"
  },
  {
    id: "EMP-005",
    employeeId: "EMP-005",
    employeeName: "Fajar Nugraha",
    department: "Engineering",
    position: "QA Engineer",
    directManager: "Budi Santoso",
    contractType: "PKWT I",
    contractNumber: "134/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-14",
    contractEndDate: "2026-07-13",
    daysRemaining: 13,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.UnderDiscussion,
    negotiationNotes: "User merekomendasikan kenaikan, namun Head HR masih mereview kelayakan budget departemen.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Approved,
    headHRReview: ApprovalStatus.Pending,
    contractDraftDate: "2026-06-28",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.WaitingHeadHRReview,
    salaryNegotiationStatus: SalaryNegotiationStatus.UnderDiscussion,
    hrPic: "Siti Rahma",
    notes: "User merekomendasikan extend dengan penyesuaian kompensasi, namun Head HR masih mereview kelayakan budget departemen.",
    priority: "High"
  },
  {
    id: "EMP-006",
    employeeId: "EMP-006",
    employeeName: "Linda Wijaya",
    department: "Human Resources",
    position: "HR Recruiter",
    directManager: "Siti Rahma",
    contractType: "PKWT I",
    contractNumber: "145/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-21",
    contractEndDate: "2026-07-20",
    daysRemaining: 20,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.WaitingPayroll,
    negotiationNotes: "Proses drafting perpanjangan kontrak sedang dilakukan oleh HR Admin.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Approved,
    headHRReview: ApprovalStatus.Approved,
    contractDraftDate: "2026-06-30",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.ContractDrafting,
    salaryNegotiationStatus: SalaryNegotiationStatus.WaitingPayroll,
    hrPic: "Rian Hidayat",
    notes: "Proses drafting perpanjangan kontrak sedang dilakukan oleh HR Admin.",
    priority: "High"
  },
  {
    id: "EMP-007",
    employeeId: "EMP-007",
    employeeName: "Andi Wijaya",
    department: "Sales",
    position: "Account Executive",
    directManager: "Hendra Wijaya",
    contractType: "PKWT I",
    contractNumber: "155/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-26",
    contractEndDate: "2026-07-25",
    daysRemaining: 25,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.WaitingManagement,
    negotiationNotes: "Menunggu approval dari Direktur Operasional untuk compensation adjustment AE berprestasi. Nominal tidak dicatat di sistem ini.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.Extend,
    directorApproval: ApprovalStatus.Pending,
    headHRReview: ApprovalStatus.None,
    contractDraftDate: "",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.WaitingDirectorApproval,
    salaryNegotiationStatus: SalaryNegotiationStatus.WaitingManagement,
    hrPic: "Siti Rahma",
    notes: "Menunggu approval dari Direktur Operasional untuk compensation adjustment AE berprestasi. Nominal tidak dicatat di sistem ini.",
    priority: "High"
  },
  {
    id: "EMP-008",
    employeeId: "EMP-008",
    employeeName: "Rina Permata",
    department: "Operations",
    position: "Customer Service Agent",
    directManager: "Joko Susilo",
    contractType: "PKWT I",
    contractNumber: "189/HRD-PKWT/VIII/2025",
    contractStartDate: "2025-08-06",
    contractEndDate: "2026-08-05",
    daysRemaining: 36,
    compensationReviewNeeded: false,
    negotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    negotiationNotes: "",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    headHRReview: ApprovalStatus.None,
    contractDraftDate: "",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.WaitingUserReview,
    salaryNegotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    hrPic: "Rian Hidayat",
    notes: "Sudah dikirim form evaluasi ke Pak Joko Susilo untuk mereview kinerja Rina.",
    priority: "Medium"
  },
  {
    id: "EMP-009",
    employeeId: "EMP-009",
    employeeName: "Eko Prasetyo",
    department: "Product",
    position: "Product Owner",
    directManager: "Anisa Rahmawati",
    contractType: "PKWT I",
    contractNumber: "199/HRD-PKWT/VIII/2025",
    contractStartDate: "2025-08-21",
    contractEndDate: "2026-08-20",
    daysRemaining: 51,
    compensationReviewNeeded: false,
    negotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    negotiationNotes: "",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    headHRReview: ApprovalStatus.None,
    contractDraftDate: "",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.NeedReview,
    salaryNegotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    hrPic: "Siti Rahma",
    notes: "Kontrak H-51, masuk daftar list pemicu notifikasi awal ke HR PIC.",
    priority: "Medium"
  },
  {
    id: "EMP-010",
    employeeId: "EMP-010",
    employeeName: "Kartika Sari",
    department: "Finance & Accounting",
    position: "Senior Accountant",
    directManager: "Megawati Kusuma",
    contractType: "PKWT II",
    contractNumber: "005/HRD-PKWT/X/2024",
    contractStartDate: "2024-10-01",
    contractEndDate: "2026-09-30",
    daysRemaining: 92,
    compensationReviewNeeded: false,
    negotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    negotiationNotes: "",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    headHRReview: ApprovalStatus.None,
    contractDraftDate: "",
    contractSentDate: "",
    signedDeadline: "",
    signedReceivedDate: "",
    contractStatus: ContractStatus.Active,
    salaryNegotiationStatus: SalaryNegotiationStatus.NoNegotiation,
    hrPic: "Rian Hidayat",
    notes: "Kinerja sangat bagus. Masih aman di atas 60 hari.",
    priority: "Low"
  },
  {
    id: "EMP-011",
    employeeId: "EMP-011",
    employeeName: "Rudi Hartono",
    department: "Engineering",
    position: "DevOps Engineer",
    directManager: "Budi Santoso",
    contractType: "PKWT I",
    contractNumber: "111/HRD-PKWT/VII/2025",
    contractStartDate: "2025-07-01",
    contractEndDate: "2026-06-30",
    daysRemaining: 0,
    compensationReviewNeeded: true,
    negotiationStatus: SalaryNegotiationStatus.Resolved,
    negotiationNotes: "Pengangkatan tetap, negosiasi compensation review resolved.",
    payrollFollowUpNotes: "",
    userRecommendation: UserRecommendation.ConvertToPermanent,
    directorApproval: ApprovalStatus.Approved,
    headHRReview: ApprovalStatus.Approved,
    contractDraftDate: "2026-06-25",
    contractSentDate: "2026-06-26",
    signedDeadline: "2026-06-30",
    signedReceivedDate: "2026-06-30",
    contractStatus: ContractStatus.ConvertedToPermanent,
    salaryNegotiationStatus: SalaryNegotiationStatus.Resolved,
    hrPic: "Siti Rahma",
    notes: "Sudah selesai proses pengangkatan jadi karyawan tetap per hari ini 30 Juni 2026.",
    priority: "Low"
  }
];

export const INITIAL_PROBATIONS: ProbationItem[] = [
  {
    id: "PRB-001",
    employeeId: "PRB-001",
    employeeName: "Hendra Wijaya",
    department: "Engineering",
    position: "Backend Developer",
    directManager: "Budi Santoso",
    probationStartDate: "2026-03-21",
    probationEndDate: "2026-06-20",
    daysRemaining: -10,
    reviewFormStatus: "Sent to User",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    finalDecision: "",
    newEmploymentStatus: "",
    hrPic: "Siti Rahma",
    notes: "OVERDUE! Probation selesai 20 Juni tapi form review belum dikembalikan oleh Pak Budi.",
    probationStatus: ProbationStatus.Overdue,
    priority: "Overdue"
  },
  {
    id: "PRB-002",
    employeeId: "PRB-002",
    employeeName: "Wati Setiawati",
    department: "Marketing",
    position: "Copywriter",
    directManager: "Indah Wahyuni",
    probationStartDate: "2026-04-04",
    probationEndDate: "2026-07-03",
    daysRemaining: 3,
    reviewFormStatus: "Completed",
    userRecommendation: UserRecommendation.PassProbation,
    directorApproval: ApprovalStatus.Approved,
    finalDecision: "Passed",
    newEmploymentStatus: "Permanent Employee",
    hrPic: "Rian Hidayat",
    notes: "CRITICAL! Hasil review lolos probation, tinggal disiapkan SK Pengangkatan Tetap sebelum 3 Juli.",
    probationStatus: ProbationStatus.Critical,
    priority: "Critical"
  },
  {
    id: "PRB-003",
    employeeId: "PRB-003",
    employeeName: "Bambang Pamungkas",
    department: "Sales",
    position: "Senior Sales Exec",
    directManager: "Hendra Wijaya",
    probationStartDate: "2026-04-11",
    probationEndDate: "2026-07-10",
    daysRemaining: 10,
    reviewFormStatus: "Completed",
    userRecommendation: UserRecommendation.PassProbation,
    directorApproval: ApprovalStatus.Pending,
    finalDecision: "",
    newEmploymentStatus: "",
    hrPic: "Siti Rahma",
    notes: "Rekomendasi Lolos, sedang dalam antrian approval Direktur Utama.",
    probationStatus: ProbationStatus.WaitingDirectorApproval,
    priority: "High"
  },
  {
    id: "PRB-004",
    employeeId: "PRB-004",
    employeeName: "Jessica Putri",
    department: "Human Resources",
    position: "HR Generalist",
    directManager: "Siti Rahma",
    probationStartDate: "2026-04-17",
    probationEndDate: "2026-07-16",
    daysRemaining: 16,
    reviewFormStatus: "Pending",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    finalDecision: "",
    newEmploymentStatus: "",
    hrPic: "Rian Hidayat",
    notes: "Menunggu rekomendasi formal dari Lead HR (Siti Rahma). Form evaluasi sedang diisi.",
    probationStatus: ProbationStatus.WaitingUserRecommendation,
    priority: "High"
  },
  {
    id: "PRB-005",
    employeeId: "PRB-005",
    employeeName: "Dedi Setiadi",
    department: "Operations",
    position: "Warehouse Staff",
    directManager: "Joko Susilo",
    probationStartDate: "2026-04-26",
    probationEndDate: "2026-07-25",
    daysRemaining: 25,
    reviewFormStatus: "Sent to User",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    finalDecision: "",
    newEmploymentStatus: "",
    hrPic: "Siti Rahma",
    notes: "Form evaluasi probation sudah dikirim ke manager pergudangan.",
    probationStatus: ProbationStatus.WaitingReviewForm,
    priority: "Medium"
  },
  {
    id: "PRB-006",
    employeeId: "PRB-006",
    employeeName: "Anindya Kusuma",
    department: "Product",
    position: "UI/UX Designer",
    directManager: "Anisa Rahmawati",
    probationStartDate: "2026-05-12",
    probationEndDate: "2026-08-10",
    daysRemaining: 41,
    reviewFormStatus: "Not Sent",
    userRecommendation: UserRecommendation.None,
    directorApproval: ApprovalStatus.None,
    finalDecision: "",
    newEmploymentStatus: "",
    hrPic: "Rian Hidayat",
    notes: "Masuk tahap monitoring tengah periode probation. Masih aman.",
    probationStatus: ProbationStatus.NeedReview,
    priority: "Medium"
  }
];

export const DEPARTMENTS = [
  "All Departments",
  "Engineering",
  "Marketing",
  "Sales",
  "Operations",
  "Finance & Accounting",
  "Human Resources",
  "Product"
];

export const HR_PICS = [
  "All HR PICs",
  "Siti Rahma",
  "Rian Hidayat",
  "Ahmad Fauzi"
];
